apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: min-ia
  namespace: teamia
  labels:
    team: arbeidsgiver
spec:
  image: {{image}}
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
