apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: min-ia
  namespace: teamia
  labels:
    team: teamia
spec:
  image: {{image}}
  liveness:
    path: "/min-ia/internal/isAlive"
    port: 8080
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/min-ia/internal/isReady"
    port: 8080
    initialDelay: 20
    timeout: 60
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
