apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: min-ia
  namespace: teamia
  labels:
    team: teamia
spec:
  image: {{image}}
  liveness:
    path: "/internal/isAlive"
    initialDelay: 20
  readiness:
    path: "/internal/isReady"
    initialDelay: 20
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
