name: Build and deploy min-ia
on: [push]
env:
  "IMAGE": "ghcr.io/${{ github.repository }}:${{ github.sha }}"

concurrency:
  group: build-deploy-on-${{ github.ref }}
  cancel-in-progress: true

jobs:
  compile-test-and-build:
    name: Build and run tests
    runs-on: Ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - uses: actions/cache@v2
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node-cache-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-cache-
      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
      - name: Build application
        run: |
          yarn run build
      - name: Build tag and push Docker container
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker build . -t ${IMAGE}
          echo ${GITHUB_TOKEN} | docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} --password-stdin
          echo ${IMAGE}
          docker push ${IMAGE}
